#!/usr/bin/env ruby

timestamp = Time.now.utc.strftime("%Y-%m-%d-%H-%M-%S")
filename = "microstream-#{timestamp}.md"
path = File.join("microstreams", filename)

content = <<~EOF
---
title: Microstream #{timestamp}
date: #{Time.now.utc}
---

Autogenerated microstream pulse emitted from Node-01.
EOF

File.write(path, content)

puts "Generated #{path}"
